// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type BoomboxBox struct {
	BoxID     int64
	UserID    int64
	BoxName   string
	ImageUrl  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type BoomboxBoxItem struct {
	BoxID     int64
	ItemID    int64
	Quantity  int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type BoomboxItem struct {
	ItemID    int64
	ItemName  string
	CreatedAt time.Time
}

type BoomboxOauthAccount struct {
	OauthAccountID int64
	UserID         int64
	Provider       string
	ProviderUserID string
	ProviderLogin  sql.NullString
	ProviderEmail  sql.NullString
	AccessToken    string
	RefreshToken   sql.NullString
	TokenType      string
	Scope          sql.NullString
	ExpiresAt      sql.NullTime
	RevokedAt      sql.NullTime
	LastUsedAt     sql.NullTime
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type BoomboxUser struct {
	UserID      int64
	Username    string
	DisplayName sql.NullString
	IsActive    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
