// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// ==========================================
	// BOX_ITEM (JUNCTION)
	// ==========================================
	AddItemToBoxByIDs(ctx context.Context, arg AddItemToBoxByIDsParams) (BoomboxBoxItem, error)
	AddItemToBoxByImageURL(ctx context.Context, arg AddItemToBoxByImageURLParams) (BoomboxBoxItem, error)
	// ==========================================
	// BOX
	// ==========================================
	CreateBox(ctx context.Context, arg CreateBoxParams) (BoomboxBox, error)
	// ==========================================
	// ITEM
	// ==========================================
	CreateItem(ctx context.Context, itemName string) (BoomboxItem, error)
	// ==========================================
	// USERS
	// ==========================================
	CreateUser(ctx context.Context, arg CreateUserParams) (BoomboxUser, error)
	DeactivateUser(ctx context.Context, userID int64) (BoomboxUser, error)
	DeleteBox(ctx context.Context, boxID int64) error
	DeleteZeroQuantityBoxItems(ctx context.Context) (int64, error)
	GetBoxByID(ctx context.Context, boxID int64) (BoomboxBox, error)
	GetBoxByImageURL(ctx context.Context, imageUrl string) (BoomboxBox, error)
	GetBoxContentsByBoxID(ctx context.Context, boxID int64) ([]GetBoxContentsByBoxIDRow, error)
	GetBoxContentsByImageURL(ctx context.Context, imageUrl string) ([]GetBoxContentsByImageURLRow, error)
	GetItemByName(ctx context.Context, itemName string) (BoomboxItem, error)
	GetOAuthAccountByProviderUserID(ctx context.Context, providerUserID string) (BoomboxOauthAccount, error)
	GetOAuthAccountByUserID(ctx context.Context, userID int64) (BoomboxOauthAccount, error)
	GetUserByID(ctx context.Context, userID int64) (BoomboxUser, error)
	GetUserByUsername(ctx context.Context, username string) (BoomboxUser, error)
	ListBoxesByUser(ctx context.Context, userID int64) ([]BoomboxBox, error)
	ListItems(ctx context.Context) ([]BoomboxItem, error)
	RemoveBoxItemByIDs(ctx context.Context, arg RemoveBoxItemByIDsParams) error
	RemoveItemFromBoxByImageURL(ctx context.Context, arg RemoveItemFromBoxByImageURLParams) (int64, error)
	RenameBox(ctx context.Context, arg RenameBoxParams) (BoomboxBox, error)
	RevokeOAuthAccount(ctx context.Context, oauthAccountID int64) (BoomboxOauthAccount, error)
	SetBoxItemQuantityByIDs(ctx context.Context, arg SetBoxItemQuantityByIDsParams) (BoomboxBoxItem, error)
	UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) (BoomboxUser, error)
	// ==========================================
	// OAUTH ACCOUNT
	// ==========================================
	UpsertGithubOAuthAccount(ctx context.Context, arg UpsertGithubOAuthAccountParams) (BoomboxOauthAccount, error)
}

var _ Querier = (*Queries)(nil)
