// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const addItemToBoxByIDs = `-- name: AddItemToBoxByIDs :one

INSERT INTO boombox.box_item (box_id, item_id, quantity)
VALUES ($1, $2, $3)
ON CONFLICT (box_id, item_id)
DO UPDATE SET
    quantity = boombox.box_item.quantity + EXCLUDED.quantity,
    updated_at = now()
RETURNING box_id, item_id, quantity, created_at, updated_at
`

type AddItemToBoxByIDsParams struct {
	BoxID    int64
	ItemID   int64
	Quantity int32
}

// ==========================================
// BOX_ITEM (JUNCTION)
// ==========================================
func (q *Queries) AddItemToBoxByIDs(ctx context.Context, arg AddItemToBoxByIDsParams) (BoomboxBoxItem, error) {
	row := q.db.QueryRowContext(ctx, addItemToBoxByIDs, arg.BoxID, arg.ItemID, arg.Quantity)
	var i BoomboxBoxItem
	err := row.Scan(
		&i.BoxID,
		&i.ItemID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addItemToBoxByImageURL = `-- name: AddItemToBoxByImageURL :one
WITH target_box AS (
    SELECT box_id FROM boombox.box WHERE image_url = $1
),
target_item AS (
    INSERT INTO boombox.item (item_name)
    VALUES ($2)
    ON CONFLICT (item_name) DO UPDATE SET item_name = EXCLUDED.item_name
    RETURNING item_id
)
INSERT INTO boombox.box_item (box_id, item_id, quantity)
SELECT tb.box_id, ti.item_id, $3
FROM target_box tb
CROSS JOIN target_item ti
ON CONFLICT (box_id, item_id)
DO UPDATE SET
    quantity = boombox.box_item.quantity + EXCLUDED.quantity,
    updated_at = now()
RETURNING box_id, item_id, quantity, created_at, updated_at
`

type AddItemToBoxByImageURLParams struct {
	ImageUrl string
	ItemName string
	Quantity int32
}

func (q *Queries) AddItemToBoxByImageURL(ctx context.Context, arg AddItemToBoxByImageURLParams) (BoomboxBoxItem, error) {
	row := q.db.QueryRowContext(ctx, addItemToBoxByImageURL, arg.ImageUrl, arg.ItemName, arg.Quantity)
	var i BoomboxBoxItem
	err := row.Scan(
		&i.BoxID,
		&i.ItemID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBox = `-- name: CreateBox :one

INSERT INTO boombox.box (user_id, box_name, image_url)
VALUES ($1, $2, $3)
RETURNING box_id, user_id, box_name, image_url, created_at, updated_at
`

type CreateBoxParams struct {
	UserID   int64
	BoxName  string
	ImageUrl string
}

// ==========================================
// BOX
// ==========================================
func (q *Queries) CreateBox(ctx context.Context, arg CreateBoxParams) (BoomboxBox, error) {
	row := q.db.QueryRowContext(ctx, createBox, arg.UserID, arg.BoxName, arg.ImageUrl)
	var i BoomboxBox
	err := row.Scan(
		&i.BoxID,
		&i.UserID,
		&i.BoxName,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createItem = `-- name: CreateItem :one

INSERT INTO boombox.item (item_name)
VALUES ($1)
RETURNING item_id, item_name, created_at
`

// ==========================================
// ITEM
// ==========================================
func (q *Queries) CreateItem(ctx context.Context, itemName string) (BoomboxItem, error) {
	row := q.db.QueryRowContext(ctx, createItem, itemName)
	var i BoomboxItem
	err := row.Scan(&i.ItemID, &i.ItemName, &i.CreatedAt)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO boombox.users (username, display_name)
VALUES ($1, $2)
RETURNING user_id, username, display_name, is_active, created_at, updated_at
`

type CreateUserParams struct {
	Username    string
	DisplayName sql.NullString
}

// ==========================================
// USERS
// ==========================================
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (BoomboxUser, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.DisplayName)
	var i BoomboxUser
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :one
UPDATE boombox.users
SET is_active = false,
    updated_at = now()
WHERE user_id = $1
RETURNING user_id, username, display_name, is_active, created_at, updated_at
`

func (q *Queries) DeactivateUser(ctx context.Context, userID int64) (BoomboxUser, error) {
	row := q.db.QueryRowContext(ctx, deactivateUser, userID)
	var i BoomboxUser
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBox = `-- name: DeleteBox :exec
DELETE FROM boombox.box
WHERE box_id = $1
`

func (q *Queries) DeleteBox(ctx context.Context, boxID int64) error {
	_, err := q.db.ExecContext(ctx, deleteBox, boxID)
	return err
}

const deleteZeroQuantityBoxItems = `-- name: DeleteZeroQuantityBoxItems :execrows
DELETE FROM boombox.box_item
WHERE quantity = 0
`

func (q *Queries) DeleteZeroQuantityBoxItems(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteZeroQuantityBoxItems)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBoxByID = `-- name: GetBoxByID :one
SELECT box_id, user_id, box_name, image_url, created_at, updated_at
FROM boombox.box
WHERE box_id = $1
`

func (q *Queries) GetBoxByID(ctx context.Context, boxID int64) (BoomboxBox, error) {
	row := q.db.QueryRowContext(ctx, getBoxByID, boxID)
	var i BoomboxBox
	err := row.Scan(
		&i.BoxID,
		&i.UserID,
		&i.BoxName,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBoxByImageURL = `-- name: GetBoxByImageURL :one
SELECT box_id, user_id, box_name, image_url, created_at, updated_at
FROM boombox.box
WHERE image_url = $1
`

func (q *Queries) GetBoxByImageURL(ctx context.Context, imageUrl string) (BoomboxBox, error) {
	row := q.db.QueryRowContext(ctx, getBoxByImageURL, imageUrl)
	var i BoomboxBox
	err := row.Scan(
		&i.BoxID,
		&i.UserID,
		&i.BoxName,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBoxContentsByBoxID = `-- name: GetBoxContentsByBoxID :many
SELECT
    b.box_id,
    b.box_name,
    b.image_url,
    i.item_id,
    i.item_name,
    bi.quantity,
    bi.updated_at
FROM boombox.box b
JOIN boombox.box_item bi ON bi.box_id = b.box_id
JOIN boombox.item i ON i.item_id = bi.item_id
WHERE b.box_id = $1
ORDER BY i.item_name
`

type GetBoxContentsByBoxIDRow struct {
	BoxID     int64
	BoxName   string
	ImageUrl  string
	ItemID    int64
	ItemName  string
	Quantity  int32
	UpdatedAt time.Time
}

func (q *Queries) GetBoxContentsByBoxID(ctx context.Context, boxID int64) ([]GetBoxContentsByBoxIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getBoxContentsByBoxID, boxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBoxContentsByBoxIDRow
	for rows.Next() {
		var i GetBoxContentsByBoxIDRow
		if err := rows.Scan(
			&i.BoxID,
			&i.BoxName,
			&i.ImageUrl,
			&i.ItemID,
			&i.ItemName,
			&i.Quantity,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBoxContentsByImageURL = `-- name: GetBoxContentsByImageURL :many
SELECT
    b.box_id,
    b.box_name,
    b.image_url,
    i.item_id,
    i.item_name,
    bi.quantity,
    bi.updated_at
FROM boombox.box b
JOIN boombox.box_item bi ON bi.box_id = b.box_id
JOIN boombox.item i ON i.item_id = bi.item_id
WHERE b.image_url = $1
ORDER BY i.item_name
`

type GetBoxContentsByImageURLRow struct {
	BoxID     int64
	BoxName   string
	ImageUrl  string
	ItemID    int64
	ItemName  string
	Quantity  int32
	UpdatedAt time.Time
}

func (q *Queries) GetBoxContentsByImageURL(ctx context.Context, imageUrl string) ([]GetBoxContentsByImageURLRow, error) {
	rows, err := q.db.QueryContext(ctx, getBoxContentsByImageURL, imageUrl)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBoxContentsByImageURLRow
	for rows.Next() {
		var i GetBoxContentsByImageURLRow
		if err := rows.Scan(
			&i.BoxID,
			&i.BoxName,
			&i.ImageUrl,
			&i.ItemID,
			&i.ItemName,
			&i.Quantity,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemByName = `-- name: GetItemByName :one
SELECT item_id, item_name, created_at
FROM boombox.item
WHERE item_name = $1
`

func (q *Queries) GetItemByName(ctx context.Context, itemName string) (BoomboxItem, error) {
	row := q.db.QueryRowContext(ctx, getItemByName, itemName)
	var i BoomboxItem
	err := row.Scan(&i.ItemID, &i.ItemName, &i.CreatedAt)
	return i, err
}

const getOAuthAccountByProviderUserID = `-- name: GetOAuthAccountByProviderUserID :one
SELECT
    oauth_account_id, user_id, provider, provider_user_id, provider_login, provider_email,
    access_token, refresh_token, token_type, scope, expires_at, revoked_at, last_used_at,
    created_at, updated_at
FROM boombox.oauth_account
WHERE provider = 'github'
  AND provider_user_id = $1
`

func (q *Queries) GetOAuthAccountByProviderUserID(ctx context.Context, providerUserID string) (BoomboxOauthAccount, error) {
	row := q.db.QueryRowContext(ctx, getOAuthAccountByProviderUserID, providerUserID)
	var i BoomboxOauthAccount
	err := row.Scan(
		&i.OauthAccountID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderLogin,
		&i.ProviderEmail,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenType,
		&i.Scope,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthAccountByUserID = `-- name: GetOAuthAccountByUserID :one
SELECT
    oauth_account_id, user_id, provider, provider_user_id, provider_login, provider_email,
    access_token, refresh_token, token_type, scope, expires_at, revoked_at, last_used_at,
    created_at, updated_at
FROM boombox.oauth_account
WHERE user_id = $1
  AND provider = 'github'
`

func (q *Queries) GetOAuthAccountByUserID(ctx context.Context, userID int64) (BoomboxOauthAccount, error) {
	row := q.db.QueryRowContext(ctx, getOAuthAccountByUserID, userID)
	var i BoomboxOauthAccount
	err := row.Scan(
		&i.OauthAccountID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderLogin,
		&i.ProviderEmail,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenType,
		&i.Scope,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, username, display_name, is_active, created_at, updated_at
FROM boombox.users
WHERE user_id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, userID int64) (BoomboxUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userID)
	var i BoomboxUser
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT user_id, username, display_name, is_active, created_at, updated_at
FROM boombox.users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (BoomboxUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i BoomboxUser
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBoxesByUser = `-- name: ListBoxesByUser :many
SELECT box_id, user_id, box_name, image_url, created_at, updated_at
FROM boombox.box
WHERE user_id = $1
ORDER BY box_name
`

func (q *Queries) ListBoxesByUser(ctx context.Context, userID int64) ([]BoomboxBox, error) {
	rows, err := q.db.QueryContext(ctx, listBoxesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoomboxBox
	for rows.Next() {
		var i BoomboxBox
		if err := rows.Scan(
			&i.BoxID,
			&i.UserID,
			&i.BoxName,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT item_id, item_name, created_at
FROM boombox.item
ORDER BY item_name
`

func (q *Queries) ListItems(ctx context.Context) ([]BoomboxItem, error) {
	rows, err := q.db.QueryContext(ctx, listItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoomboxItem
	for rows.Next() {
		var i BoomboxItem
		if err := rows.Scan(&i.ItemID, &i.ItemName, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeBoxItemByIDs = `-- name: RemoveBoxItemByIDs :exec
DELETE FROM boombox.box_item
WHERE box_id = $1
  AND item_id = $2
`

type RemoveBoxItemByIDsParams struct {
	BoxID  int64
	ItemID int64
}

func (q *Queries) RemoveBoxItemByIDs(ctx context.Context, arg RemoveBoxItemByIDsParams) error {
	_, err := q.db.ExecContext(ctx, removeBoxItemByIDs, arg.BoxID, arg.ItemID)
	return err
}

const removeItemFromBoxByImageURL = `-- name: RemoveItemFromBoxByImageURL :execrows
WITH target AS (
    SELECT bi.box_id, bi.item_id
    FROM boombox.box_item bi
    JOIN boombox.box b ON b.box_id = bi.box_id
    JOIN boombox.item i ON i.item_id = bi.item_id
    WHERE b.image_url = $1
      AND i.item_name = $2
      AND bi.quantity >= $3
)
UPDATE boombox.box_item bi
SET quantity = bi.quantity - $3,
    updated_at = now()
FROM target t
WHERE bi.box_id = t.box_id
  AND bi.item_id = t.item_id
`

type RemoveItemFromBoxByImageURLParams struct {
	ImageUrl string
	ItemName string
	Quantity int32
}

func (q *Queries) RemoveItemFromBoxByImageURL(ctx context.Context, arg RemoveItemFromBoxByImageURLParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeItemFromBoxByImageURL, arg.ImageUrl, arg.ItemName, arg.Quantity)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const renameBox = `-- name: RenameBox :one
UPDATE boombox.box
SET box_name = $2,
    updated_at = now()
WHERE box_id = $1
RETURNING box_id, user_id, box_name, image_url, created_at, updated_at
`

type RenameBoxParams struct {
	BoxID   int64
	BoxName string
}

func (q *Queries) RenameBox(ctx context.Context, arg RenameBoxParams) (BoomboxBox, error) {
	row := q.db.QueryRowContext(ctx, renameBox, arg.BoxID, arg.BoxName)
	var i BoomboxBox
	err := row.Scan(
		&i.BoxID,
		&i.UserID,
		&i.BoxName,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeOAuthAccount = `-- name: RevokeOAuthAccount :one
UPDATE boombox.oauth_account
SET revoked_at = now(),
    updated_at = now()
WHERE oauth_account_id = $1
RETURNING
    oauth_account_id, user_id, provider, provider_user_id, provider_login, provider_email,
    access_token, refresh_token, token_type, scope, expires_at, revoked_at, last_used_at,
    created_at, updated_at
`

func (q *Queries) RevokeOAuthAccount(ctx context.Context, oauthAccountID int64) (BoomboxOauthAccount, error) {
	row := q.db.QueryRowContext(ctx, revokeOAuthAccount, oauthAccountID)
	var i BoomboxOauthAccount
	err := row.Scan(
		&i.OauthAccountID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderLogin,
		&i.ProviderEmail,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenType,
		&i.Scope,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setBoxItemQuantityByIDs = `-- name: SetBoxItemQuantityByIDs :one
UPDATE boombox.box_item
SET quantity = $3,
    updated_at = now()
WHERE box_id = $1
  AND item_id = $2
RETURNING box_id, item_id, quantity, created_at, updated_at
`

type SetBoxItemQuantityByIDsParams struct {
	BoxID    int64
	ItemID   int64
	Quantity int32
}

func (q *Queries) SetBoxItemQuantityByIDs(ctx context.Context, arg SetBoxItemQuantityByIDsParams) (BoomboxBoxItem, error) {
	row := q.db.QueryRowContext(ctx, setBoxItemQuantityByIDs, arg.BoxID, arg.ItemID, arg.Quantity)
	var i BoomboxBoxItem
	err := row.Scan(
		&i.BoxID,
		&i.ItemID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :one
UPDATE boombox.users
SET display_name = $2,
    updated_at = now()
WHERE user_id = $1
RETURNING user_id, username, display_name, is_active, created_at, updated_at
`

type UpdateUserDisplayNameParams struct {
	UserID      int64
	DisplayName sql.NullString
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) (BoomboxUser, error) {
	row := q.db.QueryRowContext(ctx, updateUserDisplayName, arg.UserID, arg.DisplayName)
	var i BoomboxUser
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGithubOAuthAccount = `-- name: UpsertGithubOAuthAccount :one

INSERT INTO boombox.oauth_account (
    user_id,
    provider,
    provider_user_id,
    provider_login,
    provider_email,
    access_token,
    refresh_token,
    token_type,
    scope,
    expires_at,
    revoked_at,
    last_used_at
)
VALUES (
    $1,                 -- user_id
    'github',
    $2,                 -- provider_user_id
    $3,                 -- provider_login
    $4,                 -- provider_email
    $5,                 -- access_token
    $6,                 -- refresh_token
    COALESCE($7, 'bearer'),
    $8,                 -- scope
    $9,                 -- expires_at
    NULL,
    now()
)
ON CONFLICT (provider, provider_user_id)
DO UPDATE SET
    provider_login = EXCLUDED.provider_login,
    provider_email = EXCLUDED.provider_email,
    access_token   = EXCLUDED.access_token,
    refresh_token  = EXCLUDED.refresh_token,
    token_type     = EXCLUDED.token_type,
    scope          = EXCLUDED.scope,
    expires_at     = EXCLUDED.expires_at,
    revoked_at     = NULL,
    last_used_at   = now(),
    updated_at     = now()
RETURNING
    oauth_account_id, user_id, provider, provider_user_id, provider_login, provider_email,
    access_token, refresh_token, token_type, scope, expires_at, revoked_at, last_used_at,
    created_at, updated_at
`

type UpsertGithubOAuthAccountParams struct {
	UserID         int64
	ProviderUserID string
	ProviderLogin  sql.NullString
	ProviderEmail  sql.NullString
	AccessToken    string
	RefreshToken   sql.NullString
	Column7        interface{}
	Scope          sql.NullString
	ExpiresAt      sql.NullTime
}

// ==========================================
// OAUTH ACCOUNT
// ==========================================
func (q *Queries) UpsertGithubOAuthAccount(ctx context.Context, arg UpsertGithubOAuthAccountParams) (BoomboxOauthAccount, error) {
	row := q.db.QueryRowContext(ctx, upsertGithubOAuthAccount,
		arg.UserID,
		arg.ProviderUserID,
		arg.ProviderLogin,
		arg.ProviderEmail,
		arg.AccessToken,
		arg.RefreshToken,
		arg.Column7,
		arg.Scope,
		arg.ExpiresAt,
	)
	var i BoomboxOauthAccount
	err := row.Scan(
		&i.OauthAccountID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderLogin,
		&i.ProviderEmail,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenType,
		&i.Scope,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
